# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -  id: trailing-whitespace
    -  id: end-of-file-fixer
    -  id: check-yaml
    -  id: check-added-large-files
- repo: local
  hooks:
    - id: actionlint-docker
      name: actionlint via Docker
      description: Run actionlint in Docker container
      entry: docker.io/rhysd/actionlint:1.7.3
      language: docker_image
      types: [yaml]
      files: ^\.github/workflows/
