name: CREATE PR
description: |
  プルリクエストを作成する
inputs:
  message:
    required: true
    description: コミットメッセージ
outputs:
  branch:
    value: ${{ steps.pr.outputs.branch }}
    description: branch
runs:
  using: composite
  steps:
    - id: pr
      shell: bash
      env:
        USERNAME: github-actions[bot]
        EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        MESSAGE: ${{ inputs.message }}
        BRANCH: auto/${{ github.run_id }}/${{ github.run_attempt }}
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        echo "branch=${BRANCH}"
        echo "branch=${BRANCH}" >> "${GITHUB_OUTPUT}"
        git config user.name "${USERNAME}"
        git config user.email "${EMAIL}"
        git switch -c "${BRANCH}"
        git add .
        git commit -m "${MESSAGE}"
        git push origin "${BRANCH}"
        gh pr create --head "${BRANCH}" --title "${MESSAGE}" --body "${MESSSAGE}"
